name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest selenium
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#    - name: Install Firefox
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y firefox

    - name: Run tests
      run: |
        pytest -m planit --base-url http://jupiter.cloud.planittesting.com -n auto --html=report.html --self-contained-html --browser=firefox
      env:
        DISPLAY: :99.0
